<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Credit</name>
   <tag></tag>
   <elementGuidId>4c8abb30-fce4-4c08-b682-49910f1b048f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ASPxPageControlMaster_ASPxPageControlContent_RadGridObjects_ctl00_ctl04_TextBoxCredit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ASPxPageControlMaster_ASPxPageControlContent_RadGridObjects_ctl00_ctl04_TextBoxCredit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ASPxPageControlMaster$ASPxPageControlContent$RadGridObjects$ctl00$ctl04$TextBoxCredit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ASPxPageControlMaster_ASPxPageControlContent_RadGridObjects_ctl00_ctl04_TextBoxCredit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ASPxPageControlMaster_ASPxPageControlContent_RadGridObjects_ctl00_ctl04_TextBoxCredit&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Adjustment/iframe_Adjustment View_ctl00_ContentPlaceHolderMaster_ContentPlaceHolderContent_ASPxPopupControlAccount_CIF-1</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ASPxPageControlMaster_ASPxPageControlContent_RadGridObjects_ctl00_ctl04_TextBoxCredit']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ASPxPageControlMaster_ASPxPageControlContent_RadGridObjects_ctl00__0']/td/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td/div/div/table/tbody/tr/td/input</value>
   </webElementXpaths>
</WebElementEntity>
