<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>7b1ad85f-66dc-4011-915b-8a1c654c520b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ContentPlaceHolderMaster_RadRibbonBarUtilities']/div/div/div/div/div[4]/div[2]/div/div/a/span/span/span[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rrbButtonGroup.rrbButtonGroupHover > div.rrbButtonGroupIn > div.rrbControlGroup.rrbAbox > a.rrbButtonOut.rrbMediumButton > span.rrbButtonMid.rrbMenuButton > span.rrbButtonIn > span.rrbButtonArrow > span.rrbIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rrbIcon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolderMaster_RadRibbonBarUtilities&quot;)/div[@class=&quot;rrbContentWrapOut&quot;]/div[@class=&quot;rrbContentWrapMid&quot;]/div[@class=&quot;rrbContentWrapIn&quot;]/div[@class=&quot;rrbButtonArea&quot;]/div[@class=&quot;rrbButtonAreaIn rrbHiddenButtonAreaIn&quot;]/div[@class=&quot;rrbButtonGroup rrbButtonGroupHover&quot;]/div[@class=&quot;rrbButtonGroupIn&quot;]/div[@class=&quot;rrbControlGroup rrbAbox&quot;]/a[@class=&quot;rrbButtonOut rrbMediumButton&quot;]/span[@class=&quot;rrbButtonMid rrbMenuButton&quot;]/span[@class=&quot;rrbButtonIn&quot;]/span[@class=&quot;rrbButtonArrow&quot;]/span[@class=&quot;rrbIcon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ContentPlaceHolderMaster_RadRibbonBarUtilities']/div/div/div/div/div[4]/div[2]/div/div/a/span/span/span[3]/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjustment'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No License'])[3]/following::span[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance Limitation'])[1]/preceding::span[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No License'])[4]/preceding::span[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/a/span/span/span[3]/span</value>
   </webElementXpaths>
</WebElementEntity>
