<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Iframe_AccKey</name>
   <tag></tag>
   <elementGuidId>ccaf849b-4f22-45aa-9462-1fa37a15c8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ctl00_ContentPlaceHolderMaster_ContentPlaceHolderContent_ASPxPopupControlAccount_CIF-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
